services:
  tomcat:
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs/clusteringwebapp.war:/usr/local/tomcat/webapps/clusteringwebapp.war
    networks:
      - app-network
    depends_on:
      - mysql
    
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: MapDB
      MYSQL_USER: MapUser
      MYSQL_PASSWORD: map
    ports:
      - "3306:3306"
    volumes:
      - ./docker-config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
