# Stage 1: Build the Java application with Gradle
FROM gradle:7.2-jdk11 AS build
# Copy the Gradle wrapper and build files
COPY gradlew .
COPY gradlew.bat .
COPY gradle/ gradle/
COPY build.gradle .

# Ensure the Gradle wrapper is executable
RUN chmod +x gradlew

# Copy the source code and compile the application
COPY src/ src/
RUN ./gradlew build

# Stage 2: Setup Tomcat and deploy the application
FROM tomcat:9.0

# Set working directories for each service
WORKDIR /usr/local/tomcat
RUN apt-get update && apt-get install -y \
    mysql-server \
    openssh-server \
    supervisor

### private String DRIVER_CLASS_NAME = "com.mysql.cj.jdbc.Driver";
##private  String DBMS = "jdbc:mysql";
#private  String SERVER = "localhost";
#private  String DATABASE = "MapDB";
##private  int PORT = 3306;
##private  String USER_ID = "MapUser";
##private  String PASSWORD = "map";

# Configure SSH
RUN mkdir /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config

# Expose ports for MySQL, SSH, and Tomcat
EXPOSE 3306 22 8080

# Set working directory for MySQL and initialize
WORKDIR /var/lib/mysql
COPY init.sql /docker-entrypoint-initdb.d/

# Set working directory for Tomcat and deploy the application
WORKDIR /usr/local/tomcat
COPY --from=build /app/build/libs/clusteringwebapp.war $CATALINA_HOME/webapps/clusteringwebapp.war

# Supervisor configuration
WORKDIR /etc/supervisor/conf.d
COPY ./docker-config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Entrypoint script to start all services
WORKDIR /usr/local/bin
COPY ./docker-config/docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
